php8.3 upgrade
boesing/http-factory-multipart pull request #4
Opened 2024-10-02 14:14 UTC by larsmaedje

2024-10-04 14:08 UTC, boesing requested changes
Nice. Decent change request, thanks!
I have a few requests so that this can be merged.

I will also double check if both `psr/http-message` versions (`1.0` and `2.0`) are properly installed in CI as we should verify that we definitely support both versions.
Do we need to support both versions? Could you probably elaborate on why we have to support both? Usually, having an actual implementation of multiple major versions is tedious and I'd rather not have that here.

If there is not a strong reason why we have to support both versions, I'd drop v1.0 completely. Please let me know.

Thanks so far.

2024-10-04 14:08 UTC, boesing commented on src/ConfigProvider.php
> + * @psalm-import-type ServiceManagerConfigurationType from ConfigInterface
I am not 100% sure if I do want to have this laminas-specific dependency here.
This package does not require `laminas/laminas-servicemanager` and thus should not use anything from laminas unless its an actual dependency.

We just provide support for laminas without actually enforcing users to use laminas, therefore, we should provide the types on our own while respecting laminas specifics.

What do I mean by that? You could create a return type matching laminas requirements such as:

```php
/**
 * @psalm-type ServiceManagerConfigurationType array{factories: array<non-empty-string,callable(ContainerInterface):mixed>}
 */
```

That should provide proper return types without depending on laminas directly. For now that should already work OOTB if you use my example above as I only see inline callables.

2024-10-04 14:08 UTC, boesing commented on .gitignore
> +.idea
I personally do not like having IDE specific stuff within my `.gitignore`.

You can configure your developer machine to exclude `.idea` globally by using a global `.gitignore` which matches all projects.

The rationale here is, that if every contributor adds his own IDE specific stuff to the `.gitignore`, we end up having a bunch of stuff ignored yet not related to this project (thats stuff generated from the IDE, not from tooling around this project).

Could you remove this change?

2024-10-04 14:08 UTC, boesing commented on phpcs.xml.dist
> +        <exclude name="Squiz.Commenting.FunctionComment.MissingParamName"/>
Could you outline which line is reported so that I get an idea on why we need that here?

2024-10-04 14:08 UTC, boesing commented on src/PartOfMultipartStream.php
> +    public function write($string): int
Hm, we should have proper type-hints here:

https://github.com/php-fig/http-message/blob/402d35bcb92c70c026d1a6a9883f06b2ead23d71/src/StreamInterface.php#L115

2024-10-04 14:08 UTC, boesing commented on src/PartOfMultipartStream.php
> +    public function read($length): string
Hm, we should have proper type-hints here:

https://github.com/php-fig/http-message/blob/402d35bcb92c70c026d1a6a9883f06b2ead23d71/src/StreamInterface.php#L134

2024-10-04 14:08 UTC, boesing commented on test/integration/DependenciesFromConfigProviderExtractionTrait.php
> + * @psalm-import-type ServiceManagerConfigurationType from ConfigInterface
Works for me in `test` directory as we have service manager as `dev` dependency 👍🏼

2024-10-04 14:08 UTC, boesing commented on test/integration/SymfonyMimeMimeTypeGuesserIntegrationTest.php
> +use Boesing\Psr\Http\Message\Multipart\SymfonyMimeMimeTypeGuesser;
shouldn't be necessary as the namespace is already `Boesing\Psr\Http\Message\Multipart` but I guess that has been added by codesniffer? 🤷🏼‍♂️

2024-10-04 14:08 UTC, boesing commented on test/unit/ConfigProviderTest.php
> +use Boesing\Psr\Http\Message\Multipart\ConfigProvider;
shouldn't be necessary as the namespace is already `Boesing\Psr\Http\Message\Multipart` but I guess that has been added by codesniffer? 🤷🏼‍♂️

2024-10-04 14:08 UTC, boesing commented on test/unit/ModuleTest.php
> +use Boesing\Psr\Http\Message\Multipart\Module;
shouldn't be necessary as the namespace is already `Boesing\Psr\Http\Message\Multipart` but I guess that has been added by codesniffer? 🤷🏼‍♂️

2024-10-04 14:12 UTC, boesing commented on src/ConfigProvider.php
> + * @psalm-import-type ServiceManagerConfigurationType from ConfigInterface
Well, after double checking, this is actually my own change I haven't merged with #3
I will take that and apply the changes accordingly.

2024-10-04 14:14 UTC, boesing commented on phpcs.xml.dist
> +        <exclude name="Squiz.Commenting.FunctionComment.MissingParamName"/>
My change as well, so nvm.

2024-10-07 07:36 UTC, larsmaedje commented
Regarding the support for both 1.0 and 2.0 for the psr/http-message package:
You are right, we shouldn't support both if its not necessary, so i removed that change.

2024-10-07 21:57 UTC, boesing approved these changes

2024-10-07 21:57 UTC, merged

2024-10-07 21:57 UTC, boesing commented
Thanks, @larsmaedje!